# Generated by Django 6.0.2 on 2026-02-17 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goober',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0)),
                ('image_url', models.URLField(blank=True)),
                ('equipped_clothing', models.CharField(blank=True, max_length=100)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goobers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
