# Generated by Django 6.0.2 on 2026-02-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goober',
            name='health',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goober',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
